# Generated by Django 2.1.5 on 2019-02-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0002_auto_20190213_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='produtos/documents', verbose_name='documento'),
        ),
    ]
